#!/bing/sh
#echo "高端大气上档次，低调奢华有内涵，"
#echo "奔放洋气有深度，简约时尚国际范，"
#echo "低端粗俗甩节操，土憋矫情无下限，"
#echo "装模作样绿茶婊，外猛内柔女汉子，"
#echo "卖萌嘟嘴剪刀手，忧郁深沉无所谓，"
#echo "狂拽帅气吊炸天，冷艳高贵接地气，"
#echo "时尚亮丽小清新，可爱乡村非主流. "

#echo "借 我 三 千 虎 贲 ， 复 我 浩 荡 中 华 ；"
#echo "  剑 指 天 山 西  ，   马 踏 黑 海 北  ；"
#echo "贝 加 尔 湖 张 弓 ， 库 页 岛 上 赏 雪 ；"
#echo "  饮 马 恒 河 畔  ，   揽 月 碎 叶 城  ；"
#echo "中 南 半 岛 访 古 ， 东 京 废 墟 祭 祖 ；"
#echo "  汉  旗  指  处  ，   望  尘  逃  遁  ；"
#echo "敢 犯 中 华 天 威 者 ， 虽  远  必  诛 ！"

#echo "犯下的错误会积累，获得的成功会消失 --- 《俄罗斯方块》"
#echo "每次你失败的时候，总有几只猪在笑。 --- 《愤怒的小鸟》"
#echo "人生就是个鸟，不拼命飞就会摔死。"
#echo "过于拼命就会撞死。"
#echo "抱怨、烦躁只会死的更快，淡定、和平才能活得更久。"
#echo "早晚还得死。 --- 《Flappy bird》"

echo "                               _oo0oo_"
echo "                              o8888888o"
echo "                              88\" . \"88"
echo "                              (| -_- |)"
echo "                              0\  =  /0"
echo "                           ____/'---'\____"
echo "                         .'  \\\\|     |//  '."
echo "                        /  \\\\|||  :  |||//  \\"
echo "                       /  _||||| -:- |||||_  \\"
echo "                       |   | \\\\\\  -  /// |   |"
echo "                       | \\_|  ''\\---/''  |   |"
echo "                       \\  .-\\__  '_'  ___/-. /"
echo "                     ___'. .'  /--.--\\  '. . ___"
echo "                  .\"\" '<  '.___\\_<|>_/___.'  >' \"\"."
echo "                 | | :  '- \'.;'\\ _ /';.'/ - ' : | |"
echo "                 \\  \\ '-.   \\_ __\\ /__ _/   .-' /  /"
echo "            ======'-.____'-.___\\_____/___.-'____.-'======"
echo "                               '=---='"
echo ""
echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "                   佛祖保佑                    永无BUG"
echo "                   永不断线                    永不死机"


#echo "                                                              　　,,,::::t:MMMMMMMMMBVt:+.. "
#echo "                                                              　　 ,IVXVYIBttt+::+IVVMMMMMMRR:‘ "
#echo "                                                              　　 ,YYVYItMYti+i++:X+Rt:tXWRMR, "
#echo "                                                              　　 .YRiIYRMViitVXRWRYMI++++itMM.. "
#echo "                                                              　　　.Y+,.,X::,,,YMMMMMMMMRVItXMti "
#echo "                                                              　　　 :X+:,X:,. .,iiIRMWMMMBBRMMBY. "
#echo "                                                              　　　　tR+:I:i:+Y:IitYVYMMMMMMMMRi. "
#echo "                                                              　　　　.+RXt:,::.::XXIBMMMMMMMMM+: "
#echo "                                                              　　　　　,RRXitY+,.::RWMMMMMMMMt. "
#echo "                                                              　　　　　　VYI:::,..:tVMMMMMMBY+. "
#echo "                                                              　　　　　 .VBBW:::::,i.MMMMMBi:. "
#echo "                                                              　　　　　 .tWRRVi:::.X:VMMMMMMY. "
#echo "                                                              　　　　 ,+i+:,XYtt+:,i:,MMMBR: "
#echo "                                                              　　...VV..:..:.tt::++:+,RMYMV. "
#echo "                                                              　:M:::..:,.:,,,.+t+++Ytt.,+: "
#echo "                                                              tRt:,.:,.:,:.:+.,:++tit, "
#echo "                                                              :tXt:,:,:.:.,,+,:+YRY, "
#echo "                                                              　:++:::.,:.:.::+:iMi "
#echo "                                                              　 ,Ri:::,:::::::+Ii "
#echo "                                                              　 ,+:Xii:,,::I:tit,. "
#echo "                                                              　　 :BBt,:+::,::i+. "
#echo "                                                              　　 :BWXX::::::iX. "
#echo "                                                              　　 :BWVIi++t+:V+ "
#echo "                                                              　　　WBXtItii+iWI. "
#echo "                                                              　　　:MWIYIti+iVRY, "
#echo "                                                              　　　 RBXVYItiiIYXWI, "
#echo "                                                              　　　 :MRWWVYttttIIXWt. "
#echo "                                                              　　　 .XMBRRXIti++itIXW, "
#echo "                                                              　　　　.BMBBRVIi+::+ttXX. "
#echo "                                                              　　　　 ,MMBRXYti:::+tIW: "
#echo "                                                              　　　　　tMMRWYti+++ittXV "
#echo "                                                              　　　　　 +MRVYti+++ittWI "
#echo "                                                              　　　　　.VMWVtiiiiiitIR, "
#echo "                                                              　　　　 .XBBWVttttttttXRv "
#echo "                                                              　　　 .,WBRBXVtttttttIWt "
#echo "                                                              　　　 :RWXWBXYtttttttYR: "
#echo "                                                              　　 .iRWVIiBWYIttttttYW, "
#echo "                                                              　　.tWVYti:WRVIttittIVV　　　.:,, "
#echo "                                                              　　tWVIi++:XRVIIttttIXY　 ..:YYtYi:tittV, "
#echo "                                                              　 tXYti+++tWRVYttittYWIiIYYVItt:iXW+.... "
#echo "                                                              　:WIt+++iXRBBVYItitIYXXYti+iIYt++:IMRi:. "
#echo "                                                              .:Xti+:+tRWt:BVYItitIYWVIIIYXXWXVXYt+i+IV: "
#echo "                                                              .tYi+::IWI:::BVVItitIXBRVIt:::::::tIVXRiXt "
#echo "                                                              :Viii++i:itIXBXVttitVW,　　　　　　　 tBIX "
#echo "                                                              .XIiXIttIVRBRBIItttIRX　　　　　　　　 :VX "
#echo "                                                              .,tXXWWWVi+. RXXItiYRV　　　　　　　　　.. "
#echo "                                                              　　　　　　 ,BWYi+IRX "
#echo "                                                              　　　　　　　tBYiitWB, "
#echo "                                                              　　　　　　　.WVtiiIRI "
#echo "                                                              　　　　　　　 VWtiiiIB, "
#echo "                                                              　　　　　　　 ,BIiiiiWt "
#echo "                                                              　　　　　　　 .BViiiiYV "
#echo "                                                              　　　　　　　　XXtii+YV "
#echo "                                                              　　　　　　　　iRiii+YY "
#echo "                                                              　　　　　　　　:Btii+XI "
#echo "                                                              　　　　　　　　 Wtii+R: "
#echo "                                                              　　　　　　　　 XY+t+B. "
#echo "                                                              　　　　　　　　 YX+tYR. "
#echo "                                                              　　　　　　　　 tX+iWV "
#echo "                                                              　　　　　　　　 iXi+RI "
#echo "                                                              　　　　　　　　 tYiIXX "
#echo "                                                              　　　　　　　　,XtiIXRt. "
#echo "                                                              　　　　　　　　:BIVYRWIV "
#echo "                                                              　　　　　　　　+RYXXWiYR. "
#echo "                                                              　　　　　　　　iWIVYtXMV "
#echo "                                                              　　　　　　　　tBYItRtM+ "
#echo "                                                              　　　　　　　　XBWttX:B: "
#echo "                                                              　　　　　　　YYBXXYR:,R: "
